#!/bin/bash
#
# Lint the Lua source files before commit.
# Prevent commit if there are any warnings.

set -x

luacheck.bat -u -g .
if [ $? -ne 0 ]; then
  exit $?
fi

luajit examples/example.lua

exit $?
